import { StyleSheet, Platform } from 'react-native';
import { theme } from './theme';
import { scale, verticalScale, moderateScale } from '../utils/responsive';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },

    // ── Permission Screen ──
    permissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5F7FA',
        padding: scale(20),
    },
    permissionText: {
        fontSize: moderateScale(18),
        textAlign: 'center',
        marginBottom: verticalScale(20),
        color: '#333',
    },
    button: {
        backgroundColor: theme.colors.primary,
        padding: scale(15),
        borderRadius: scale(8),
        alignItems: 'center',
        width: '100%',
        marginBottom: verticalScale(10),
    },
    buttonText: {
        color: theme.colors.white,
        fontSize: moderateScale(16),
        fontWeight: 'bold',
    },

    // ── Camera Viewfinder ──
    scannerWrapper: {
        flex: 1,
        position: 'relative',
        backgroundColor: '#000',
    },
    cameraCloseButton: {
        position: 'absolute',
        top: Platform.OS === 'android' ? verticalScale(40) : verticalScale(20),
        left: scale(20),
        width: scale(44),
        height: scale(44),
        borderRadius: scale(22),
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    shutterContainer: {
        position: 'absolute',
        bottom: verticalScale(50),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        width: '100%',
        paddingHorizontal: scale(40),
        zIndex: 10,
    },
    galleryButton: {
        width: scale(44),
        height: scale(44),
        borderRadius: scale(22),
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    shutterButton: {
        width: scale(76),
        height: scale(76),
        borderRadius: scale(38),
        backgroundColor: 'rgba(255,255,255,0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    shutterInner: {
        width: scale(60),
        height: scale(60),
        borderRadius: scale(30),
        backgroundColor: theme.colors.white,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 20,
    },

    // ── Portal / Welcome Screen ──
    portalContainer: {
        flex: 1,
        backgroundColor: '#F5F7FA',
    },
    portalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(15),
        paddingTop: Platform.OS === 'android' ? verticalScale(10) : 0,
        height: verticalScale(60),
    },
    backButton: {
        width: scale(44),
        height: scale(44),
        justifyContent: 'center',
        alignItems: 'center',
    },
    portalTitle: {
        fontSize: moderateScale(18),
        fontWeight: 'bold',
        color: '#333',
    },
    portalBody: {
        flex: 1,
        paddingHorizontal: scale(25),
        paddingTop: verticalScale(30),
    },
    welcomeBox: {
        alignItems: 'center',
        marginBottom: verticalScale(40),
    },
    aiIconBox: {
        width: scale(80),
        height: scale(80),
        borderRadius: scale(40),
        backgroundColor: theme.colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: verticalScale(20),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    welcomeTitle: {
        fontSize: moderateScale(22),
        fontWeight: 'bold',
        color: theme.colors.primary,
        marginBottom: verticalScale(10),
    },
    welcomeDesc: {
        fontSize: moderateScale(14),
        color: '#666',
        textAlign: 'center',
        lineHeight: verticalScale(22),
    },
    portalCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.white,
        padding: scale(20),
        borderRadius: scale(20),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    cardIconBox: {
        width: scale(64),
        height: scale(64),
        borderRadius: scale(16),
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(15),
    },
    cardContent: {
        flex: 1,
    },
    cardTitle: {
        fontSize: moderateScale(16),
        fontWeight: 'bold',
        color: '#333',
        marginBottom: verticalScale(4),
    },
    cardDesc: {
        fontSize: moderateScale(12),
        color: '#888',
    },
    tipBox: {
        flexDirection: 'row',
        marginTop: verticalScale(40),
        backgroundColor: theme.colors.primaryLight,
        padding: scale(15),
        borderRadius: scale(12),
        alignItems: 'center',
    },
    tipText: {
        fontSize: moderateScale(12),
        color: theme.colors.primary,
        marginLeft: scale(10),
        flex: 1,
        lineHeight: verticalScale(18),
    },
    processingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(255,255,255,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 50,
    },
    processingText: {
        marginTop: verticalScale(15),
        fontSize: moderateScale(14),
        color: theme.colors.primary,
        fontWeight: 'bold',
    },

    // ── Mode Toggle ──
    modeToggleRow: {
        flexDirection: 'row',
        backgroundColor: theme.colors.white,
        borderRadius: scale(12),
        padding: scale(4),
        marginBottom: verticalScale(20),
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    modeTab: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: verticalScale(12),
        borderRadius: scale(10),
    },
    activeModeTab: {
        backgroundColor: theme.colors.primary,
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 2,
    },
    modeTabText: {
        fontSize: moderateScale(14),
        fontWeight: 'bold',
        color: '#888',
        marginLeft: scale(6),
    },
    activeModeTabText: {
        color: theme.colors.white,
    },

    // ── Image Grid ──
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: verticalScale(10),
    },
    gridItem: {
        width: '48%',
        height: verticalScale(110),
        backgroundColor: theme.colors.white,
        borderRadius: scale(16),
        marginBottom: verticalScale(15),
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: theme.colors.primaryLight,
        borderStyle: 'dashed',
        overflow: 'hidden',
    },
    gridItemFilled: {
        borderStyle: 'solid',
        borderColor: theme.colors.primary,
        borderWidth: 2,
    },
    gridImage: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        resizeMode: 'cover',
    },
    gridLabelContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        paddingVertical: verticalScale(4),
        alignItems: 'center',
    },
    gridLabel: {
        color: theme.colors.white,
        fontSize: moderateScale(12),
        fontWeight: 'bold',
    },
    gridDeleteBtn: {
        position: 'absolute',
        top: verticalScale(5),
        right: scale(5),
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: scale(24),
        height: scale(24),
        borderRadius: scale(12),
        justifyContent: 'center',
        alignItems: 'center',
    },
    introPrimaryButton: {
        backgroundColor: theme.colors.primary,
        flexDirection: 'row',
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(20),
        borderRadius: scale(12),
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    introPrimaryButtonText: {
        color: theme.colors.white,
        fontSize: moderateScale(16),
        fontWeight: 'bold',
    },
});
