import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { scale, verticalScale, moderateScale } from '../utils/responsive';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    headerRightAction: {
        width: scale(40),
        height: scale(40),
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: scale(20),
        backgroundColor: '#F5F7FA',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    keyboardAvoid: {
        flex: 1,
    },
    listContent: {
        paddingHorizontal: scale(16),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(20),
    },
    messageWrapper: {
        flexDirection: 'row',
        marginBottom: verticalScale(16),
        alignItems: 'flex-end',
    },
    messageWrapperUser: {
        justifyContent: 'flex-end',
    },
    messageWrapperBot: {
        justifyContent: 'flex-start',
    },
    botAvatar: {
        width: scale(32),
        height: scale(32),
        borderRadius: scale(16),
        backgroundColor: theme.colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(8),
        marginBottom: verticalScale(2),
    },
    messageBubble: {
        maxWidth: '78%',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        borderRadius: scale(22),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    userBubble: {
        backgroundColor: theme.colors.primary,
        borderBottomRightRadius: 4,
    },
    botBubble: {
        backgroundColor: theme.colors.white,
        borderBottomLeftRadius: 4,
    },
    messageText: {
        fontSize: moderateScale(15),
        lineHeight: verticalScale(22),
    },
    userText: {
        color: '#ffffff',
    },
    botText: {
        color: '#1a1a2e',
    },
    chatImage: {
        width: scale(220),
        height: scale(160),
        borderRadius: scale(12),
        marginBottom: verticalScale(10),
        backgroundColor: '#f1f5f9',
    },
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(24),
        paddingBottom: verticalScale(16),
    },
    loadingText: {
        marginLeft: scale(8),
        color: theme.colors.primary,
        fontSize: moderateScale(13),
        fontWeight: '500',
    },
    inputOuterContainer: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        backgroundColor: '#ffffff',
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.05)',
        flexDirection: 'row',
        alignItems: 'flex-end',
    },
    mediaButton: {
        width: scale(44),
        height: scale(44),
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: scale(22),
        backgroundColor: '#F5F7FA',
        marginRight: scale(8),
    },
    inputContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'flex-end',
        backgroundColor: '#F1F5F9',
        borderRadius: scale(24),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(4),
    },
    input: {
        flex: 1,
        fontSize: moderateScale(15),
        color: '#1a1a2e',
        maxHeight: verticalScale(100),
        minHeight: verticalScale(44),
        paddingHorizontal: scale(8),
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(12),
    },
    sendButton: {
        width: scale(38),
        height: scale(38),
        borderRadius: scale(19),
        backgroundColor: theme.colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: scale(4),
        marginBottom: verticalScale(3),
    },
    previewContainer: {
        flexDirection: 'row',
        paddingHorizontal: scale(16),
        paddingTop: verticalScale(10),
        paddingBottom: 0,
        backgroundColor: '#ffffff',
    },
    previewImage: {
        width: scale(64),
        height: scale(64),
        borderRadius: scale(12),
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.1)',
    },
    removePreview: {
        position: 'absolute',
        top: verticalScale(-4),
        left: scale(54),
        backgroundColor: '#ffffff',
        borderRadius: scale(14),
        elevation: 4,
    },

    // ── หน้ารายการแชท ──
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: scale(40),
    },
    emptyText: {
        fontSize: moderateScale(16),
        fontWeight: 'bold',
        color: '#94a3b8',
        marginTop: verticalScale(12),
    },
    newChatButton: {
        marginTop: verticalScale(20),
        backgroundColor: theme.colors.primary,
        paddingHorizontal: scale(24),
        paddingVertical: verticalScale(12),
        borderRadius: scale(24),
    },
    newChatButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: moderateScale(14),
    },
    sessionCard: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderRadius: scale(22),
        padding: scale(16),
        marginBottom: verticalScale(12),
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 2,
    },
    sessionCardIcon: {
        width: scale(44),
        height: scale(44),
        borderRadius: scale(12),
        backgroundColor: theme.colors.primary + '10',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(12),
    },
    sessionCardTitle: {
        fontSize: moderateScale(15),
        fontWeight: 'bold',
        color: '#1e293b',
        flex: 1,
    },
    sessionCardTime: {
        fontSize: moderateScale(11),
        color: '#94a3b8',
    },
    sessionCardLast: {
        fontSize: moderateScale(13),
        color: '#64748b',
        marginTop: verticalScale(2),
    },
    fab: {
        position: 'absolute',
        right: scale(20),
        bottom: verticalScale(20),
        width: scale(60),
        height: scale(60),
        borderRadius: scale(30),
        backgroundColor: theme.colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
    },

    // ── Markdown styles ──
    markdownBase: {
        fontSize: moderateScale(15),
        lineHeight: verticalScale(23),
        color: '#1a1a2e',
    },
    markdownBold: {
        fontWeight: 'bold' as const,
    },
    markdownHeader: {
        fontWeight: 'bold' as const,
        marginTop: verticalScale(4),
        marginBottom: verticalScale(2),
    },
    markdownEmptyLine: {
        height: verticalScale(4),
    },
    markdownBulletRow: {
        flexDirection: 'row' as const,
        marginBottom: verticalScale(2),
        paddingLeft: scale(2),
    },
    markdownBulletDot: {
        color: '#4a7c59',
        marginRight: scale(6),
        marginTop: verticalScale(1),
    },
    markdownNumberDot: {
        color: '#4a7c59',
        marginRight: scale(6),
        minWidth: scale(16),
    },
});
