import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { scale, verticalScale, moderateScale } from '../utils/responsive';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.colors.background },
    addBtnDark: {
        backgroundColor: theme.colors.white,
        width: scale(40),
        height: scale(40),
        borderRadius: scale(20),
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },

    // ── Empty State ──
    emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: scale(10) },
    emptyText: { fontSize: moderateScale(18), color: '#999', fontWeight: '600' },
    emptySubtext: { fontSize: moderateScale(14), color: '#bbb' },

    // ── Plant List ──
    plantCard: {
        backgroundColor: theme.colors.white,
        borderRadius: scale(14),
        padding: scale(14),
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(10),
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    plantIcon: {
        width: scale(52),
        height: scale(52),
        borderRadius: scale(14),
        backgroundColor: theme.colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(12),
        overflow: 'hidden',
    },
    plantThumb: { width: scale(52), height: scale(52) },
    plantName: { fontSize: moderateScale(17), fontWeight: 'bold', color: '#1a1a2e', marginBottom: verticalScale(3) },
    plantMeta: { fontSize: moderateScale(12), color: '#999' },

    // ── Timeline ──
    timelineItem: { flexDirection: 'row', marginBottom: verticalScale(5) },
    timelineLeft: { width: scale(28), alignItems: 'center' },
    timelineDot: {
        width: scale(12),
        height: scale(12),
        borderRadius: scale(6),
        backgroundColor: '#bbb',
        marginTop: verticalScale(4),
    },
    timelineLine: {
        width: 2,
        flex: 1,
        backgroundColor: '#ddd',
        marginTop: verticalScale(4),
    },
    timelineContent: {
        flex: 1,
        backgroundColor: theme.colors.white,
        borderRadius: scale(12),
        padding: scale(12),
        marginLeft: scale(8),
        marginBottom: verticalScale(10),
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 3,
    },
    timelineDate: { fontSize: moderateScale(12), color: '#888', marginBottom: verticalScale(8) },
    timelineImage: {
        width: '100%',
        height: verticalScale(180),
        borderRadius: scale(10),
        backgroundColor: theme.colors.border,
        marginBottom: verticalScale(8),
    },
    timelineNote: { fontSize: moderateScale(14), color: '#444', lineHeight: verticalScale(20), marginBottom: verticalScale(6) },
    aiBox: {
        backgroundColor: theme.colors.primaryLight,
        padding: scale(10),
        borderRadius: scale(8),
        marginTop: verticalScale(4),
    },
    aiBoxTitle: { fontSize: moderateScale(13), fontWeight: 'bold', color: theme.colors.primary, marginBottom: verticalScale(4) },
    aiBoxText: { fontSize: moderateScale(13), color: '#555', lineHeight: verticalScale(19) },

    // ── Modals ──
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: scale(20),
    },
    modalBox: {
        backgroundColor: theme.colors.white,
        borderRadius: scale(16),
        padding: scale(20),
        width: '100%',
    },
    modalTitle: { fontSize: moderateScale(20), fontWeight: 'bold', color: '#1a1a2e', marginBottom: verticalScale(15) },
    modalInput: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: scale(10),
        padding: scale(12),
        fontSize: moderateScale(16),
        marginBottom: verticalScale(15),
    },
    modalActions: { flexDirection: 'row', gap: scale(10) },
    modalCancel: {
        flex: 1,
        padding: scale(13),
        borderRadius: scale(10),
        borderWidth: 1,
        borderColor: '#ddd',
        alignItems: 'center',
    },
    modalConfirm: {
        flex: 1,
        padding: scale(13),
        borderRadius: scale(10),
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
    },

    // ── Add Entry Modal ──
    imagePickerRow: { flexDirection: 'row', gap: scale(12), marginBottom: verticalScale(15) },
    imgPickBtn: {
        flex: 1,
        padding: scale(20),
        borderRadius: scale(12),
        borderWidth: 2,
        borderColor: '#eee',
        borderStyle: 'dashed',
        alignItems: 'center',
        gap: scale(6),
    },
    imgPickText: { fontSize: moderateScale(14), color: '#666' },
    previewImage: {
        width: '100%',
        height: verticalScale(200),
        borderRadius: scale(12),
        marginBottom: verticalScale(5),
    },
    changeImgBtn: {
        alignItems: 'center',
        padding: scale(8),
        marginBottom: verticalScale(10),
    },
    noteInput: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: scale(10),
        padding: scale(12),
        fontSize: moderateScale(15),
        minHeight: verticalScale(60),
        textAlignVertical: 'top',
        marginBottom: verticalScale(15),
    },

    // ── Multi-Plot Selector ──
    plotList: {
        marginBottom: verticalScale(15),
    },
    plotCard: {
        width: scale(140),
        height: verticalScale(100),
        backgroundColor: theme.colors.white,
        borderRadius: scale(12),
        padding: scale(10),
        marginRight: scale(12),
        borderWidth: 2,
        borderColor: 'transparent',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 3,
    },
    plotCardActive: {
        borderColor: theme.colors.primary,
        backgroundColor: theme.colors.primaryLight,
    },
    plotCardTitle: {
        fontSize: moderateScale(14),
        fontWeight: 'bold',
        color: '#1a1a2e',
    },
    plotCardMeta: {
        fontSize: moderateScale(11),
        color: '#777',
    },
    addPlotCard: {
        width: scale(100),
        height: verticalScale(100),
        backgroundColor: 'rgba(46, 125, 50, 0.05)',
        borderRadius: scale(12),
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: theme.colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
