import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale, screenWidth } from '../utils/responsive';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    scrollArea: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(10),
    },
    heroCard: {
        backgroundColor: '#2E7D32',
        borderRadius: scale(28),
        padding: scale(24),
        minHeight: verticalScale(160),
        marginBottom: verticalScale(16),
        overflow: 'hidden',
        elevation: 10,
        shadowColor: '#2E7D32',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
    },
    heroContent: {
        zIndex: 2,
    },
    heroBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.2)',
        alignSelf: 'flex-start',
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(5),
        borderRadius: scale(12),
        marginBottom: verticalScale(12),
    },
    heroBadgeText: {
        color: '#fff',
        fontSize: moderateScale(12),
        fontWeight: '600',
    },
    heroTitle: {
        fontSize: moderateScale(20),
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: verticalScale(8),
    },
    heroDesc: {
        fontSize: moderateScale(13),
        color: 'rgba(255,255,255,0.85)',
        lineHeight: moderateScale(20),
        maxWidth: '85%',
    },
    heroBgIcon: {
        position: 'absolute',
        right: -20,
        bottom: -20,
        transform: [{ rotate: '-15deg' }],
        zIndex: 1,
    },
    // Monitoring Pills in Hero
    heroMonitorRow: {
        flexDirection: 'row',
        marginTop: verticalScale(16),
        gap: scale(12),
    },
    heroMonitorItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.15)',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: scale(12),
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    heroMonitorLabel: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: moderateScale(11),
        fontWeight: '600',
        marginRight: scale(6),
    },
    heroMonitorValue: {
        color: '#fff',
        fontSize: moderateScale(14),
        fontWeight: 'bold',
    },
    sectionHeader: {
        marginBottom: verticalScale(15),
        paddingHorizontal: scale(4),
    },
    sectionTitle: {
        fontSize: moderateScale(17),
        fontWeight: '700',
        color: '#1a1a2e',
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: verticalScale(10),
    },
    gridItem: {
        width: (screenWidth - scale(48)) / 2,
        backgroundColor: '#fff',
        borderRadius: scale(22),
        padding: scale(18),
        marginBottom: verticalScale(10),
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
    },
    iconBox: {
        width: scale(50),
        height: scale(50),
        borderRadius: scale(16),
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: verticalScale(10),
    },
    gridTitle: {
        fontSize: moderateScale(15),
        fontWeight: 'bold',
        color: '#1a1a2e',
        marginBottom: verticalScale(4),
    },
    gridDesc: {
        fontSize: moderateScale(11),
        color: '#666',
        lineHeight: moderateScale(15),
    },
    listCard: {
        backgroundColor: '#fff',
        borderRadius: scale(22),
        flexDirection: 'row',
        alignItems: 'center',
        padding: scale(14),
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
    },
    listIconBox: {
        width: scale(46),
        height: scale(46),
        borderRadius: scale(14),
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(12),
    },
    listCardContent: {
        flex: 1,
    },
    listCardTitle: {
        fontSize: moderateScale(15),
        fontWeight: 'bold',
        color: '#1a1a2e',
        marginBottom: verticalScale(4),
    },
    listCardDesc: {
        fontSize: moderateScale(12),
        color: '#888',
    },
    arrowBox: {
        width: scale(32),
        height: scale(32),
        borderRadius: scale(16),
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: scale(10),
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: verticalScale(15),
        paddingHorizontal: scale(2),
    },
    statCard: {
        backgroundColor: '#fff',
        borderRadius: scale(14),
        padding: scale(4),
        flex: 1,
        marginHorizontal: scale(1),
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.04)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 2,
    },
    statIconBox: {
        width: scale(30),
        height: scale(30),
        borderRadius: scale(10),
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: verticalScale(6),
    },
    statLabel: {
        fontSize: moderateScale(8.5),
        fontWeight: '600',
        color: '#888',
        marginBottom: verticalScale(2),
        textAlign: 'center',
    },
    statValue: {
        fontSize: moderateScale(13),
        fontWeight: 'bold',
        color: '#1F4E1C',
    },
    statUnit: {
        fontSize: moderateScale(8),
        color: '#aaa',
        marginTop: verticalScale(1),
    }
});
