import { StyleSheet, Platform } from 'react-native';
import { scale, verticalScale, moderateScale } from '../utils/responsive';
import { theme } from './theme';

export const profileStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    headerWrapper: {
        width: '100%',
        height: verticalScale(280),
        backgroundColor: '#2E7D32',
        borderBottomLeftRadius: scale(40),
        borderBottomRightRadius: scale(40),
        alignItems: 'center',
        position: 'relative',
        shadowColor: '#204622',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 15,
    },
    headerDecorativeCircle: {
        position: 'absolute',
        top: -scale(50),
        right: -scale(50),
        width: scale(200),
        height: scale(200),
        borderRadius: scale(100),
        backgroundColor: 'rgba(255,255,255,0.06)',
    },
    headerDecorativeCircleSmall: {
        position: 'absolute',
        bottom: verticalScale(20),
        left: -scale(30),
        width: scale(100),
        height: scale(100),
        borderRadius: scale(50),
        backgroundColor: 'rgba(255,255,255,0.04)',
    },
    profileAvatarWrapper: {
        width: scale(110),
        height: scale(110),
        borderRadius: scale(55),
        backgroundColor: '#ffffff',
        padding: scale(3),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 12,
        marginTop: verticalScale(20),
    },
    avatarImage: {
        width: '100%',
        height: '100%',
        borderRadius: scale(52),
    },
    editBadge: {
        position: 'absolute',
        bottom: scale(2),
        right: scale(2),
        backgroundColor: '#2E7D32',
        width: scale(32),
        height: scale(32),
        borderRadius: scale(16),
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#ffffff',
    },
    userInfoSection: {
        alignItems: 'center',
        marginTop: verticalScale(12),
    },
    userName: {
        fontSize: moderateScale(22),
        fontWeight: 'bold',
        color: '#ffffff',
        letterSpacing: 0.5,
    },
    userRole: {
        fontSize: moderateScale(13),
        color: 'rgba(255,255,255,0.9)',
        marginTop: verticalScale(4),
        fontWeight: '500',
    },
    // Glassmorphism Stats Card
    statsGlassContainer: {
        flexDirection: 'row',
        backgroundColor: '#ffffff',
        marginHorizontal: scale(20),
        borderRadius: scale(24),
        paddingVertical: verticalScale(16),
        paddingHorizontal: scale(12),
        marginTop: -verticalScale(35),
        justifyContent: 'space-around',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.04)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 10,
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statIconWrapper: {
        width: scale(38),
        height: scale(38),
        borderRadius: scale(12),
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: verticalScale(8),
    },
    statValue: {
        fontSize: moderateScale(17),
        fontWeight: '900',
        color: '#2E7D32',
    },
    statLabel: {
        fontSize: moderateScale(11),
        color: '#666',
        marginTop: verticalScale(2),
        fontWeight: '600',
    },
    statDivider: {
        width: 1,
        height: '50%',
        backgroundColor: 'rgba(0,0,0,0.06)',
        alignSelf: 'center',
    },
    // Menu Sections
    menuSection: {
        marginTop: verticalScale(25),
        paddingHorizontal: scale(20),
    },
    sectionTitle: {
        fontSize: moderateScale(16),
        fontWeight: 'bold',
        color: '#1A1A2E',
        marginBottom: verticalScale(12),
        marginLeft: scale(4),
    },
    menuGroup: {
        backgroundColor: '#ffffff',
        borderRadius: scale(24),
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
        elevation: 4,
        marginBottom: verticalScale(20),
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: scale(16),
    },
    menuIconBox: {
        width: scale(40),
        height: scale(40),
        borderRadius: scale(12),
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(15),
    },
    menuLabel: {
        fontSize: moderateScale(15),
        fontWeight: '600',
        color: '#333',
        flex: 1,
    },
    menuDivider: {
        height: 1,
        backgroundColor: '#F8F9FA',
        marginLeft: scale(70),
    },
    // Logout
    logoutContainer: {
        paddingHorizontal: scale(20),
        marginBottom: verticalScale(40),
    },
    logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFF5F5',
        paddingVertical: verticalScale(16),
        borderRadius: scale(20),
        borderWidth: 1,
        borderColor: '#FFE3E3',
    },
    logoutText: {
        fontSize: moderateScale(16),
        fontWeight: 'bold',
        color: '#E53935',
        marginLeft: scale(10),
    },
});
